[package]
name = "ui_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4"
async-std = "1.12.0"
dualshock-driver = {git = "https://github.com/motii8128/dualshock-driver.git"}